remote_theme: pages-themes/hacker@v0.2.0
plugins:
  - jekyll-remote-theme

title: Yu Yucaerin
description: Wandering Code Sorceress | Professional Sleeper | CVE Diver

show_downloads: true

# Optional: Social links
github:
  is_project_page: false
